### ISSUE TITLE
On FreeBSD, ocelotgui searches for libmysql.so, not libmysqlclient.so

### ISSUE THREAD

**Issue by drboone** [ocelot-inc/ocelotgui#10]
FreeBSD 14.0-RELEASE-p6.  I cloned the git repo at commit 21f3df8863816f954cd359274d4d69d1e9890910, ran cmake / make / make install.  On starting, ocelotgui presents the `Error, libmysqlclient was not found` dialog.  For the mysql 8.0 client installed from FreeBSD's pkg system, `libmysqlclient.so` ends up in `/usr/local/lib/mysql/`.  A quick truss session indicates that ocelotgui ends up searching for `libmysql.so`, not `libmysqlclient.so`.  I haven't figured out where it's getting that yet.  Hints appreciated.

Side note: Due to some sort of llvm change, I got this error during build:
`fatal error: '__string/char_traits.h' file not found`

Comment #5 here worked to get past this -
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273661

**Comment by pgulutzan** [comment]
The name is fixed in the source code (ocelotgui.cpp ldbms::ldbms_get_library) as a choice between libmysqlclient.so and libmariadbclient.so, not libmysql.so.  I'll install FreeBSD 14 and see what adjustments are necessary, it will take a few days.

**Comment by drboone** [comment]
Thanks!  The truss output contains 752 lines of various attempts to find the library, but the string "libmysqlclient" doesn't occur anywhere in the file.

**Comment by pgulutzan** [comment]
@drboone: The is not a fix but I'm able to connect ocelotgui-2.4 to MySQL-8.0 after changing several lines in ocelotgui.cpp:
starting with the latest source from github:
replace all #ifdef OCELOT_OS_LINUX with #ifdef OCELOT_OS_FREEBSD
replace all #ifdef OCELOT_OS_NONLINUX with #ifdef _WIN32
then build again, and MySQL is found.
This is with FreeBSD 14.1 + xfce.
I installed devel/qt5 and graphics/mesa-devel among other things, but I don't think the details matter, it's now clear that this specific problem happens because one or more of the #ifdefs makes ocelotgui think it's on Windows. So now I have to change ocelotgui.cpp in a proper way and push again. It still will take a few days.

**Comment by drboone** [comment]
Thanks for the analysis!  No rush.

**Comment by pgulutzan** [comment]
@drboone: With FreeBSD 14.1 + Qt 5 + MySQL 8, I can now start ocelotgui and find the library. Please download the latest source and try it.

**Comment by drboone** [comment]
Works now.  Thank you!

**Comment by pgulutzan** [comment]
@drboone: Good. I'll close this. If you like what you see, please click the GitHub "Star" button and tell others.
