### ISSUE TITLE
DEBUG: Error 1064

### ISSUE THREAD

**Issue by nobicycle** [ocelot-inc/ocelotgui#8]
Hello, and thanks for ocelotgui.

Trying debug for the first time, after connecting,  I obtain:
```
mariadb>$INSTALL
Error 1064 (42000) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'offset INT, line_number INT, valu...' at line 1
```

$ mysqld -V
mysqld  Ver 10.7.3-MariaDB for Linux on x86_64 (Arch Linux)
$ uname -a
Linux tower 5.10.109-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:20 UTC 2022 x86_64 GNU/Linux

**Comment by pgulutzan** [comment]
Thanks for noticing. The $install is failing because we try to create a table with a column named OFFSET. That was okay in MariaDB 10.5 but now I see that MariaDB has decided OFFSET is a reserved word. That's easy to fix ... but then it turns out that there's another problem with MariaDB 10.7 only, which I'll look at tomorrow, it looks like a workaround is necessary for a new server bug. I'm hopeful that there will be a source-code patch available within a couple of days.

**Comment by pgulutzan** [comment]
Today i pushed a change https://github.com/ocelot-inc/ocelotgui/commit/7af8302341511da3f868576c73a1e966862fc680.
This changes two source-code files -- so far the change has only been done in the source code which can be pulled from our github repository.
Are you able to build from source again and see whether $install works now for you?

**Comment by nobicycle** [comment]
Thank you for the fix.
Below is the output. Seems to work. 
Regards

```

mariadb>$install
OK 0 rows affected (1.0 seconds)
```

**Comment by pgulutzan** [comment]
Good, I regard this as fixed in the source, and the fix will be incorporated in the next release.
Additionally -- I hope this is interesting news for Manjaro users -- I have added a PKGBUILD file which should be useful for making ocelotgui as a pacman-compatible package.
https://github.com/ocelot-inc/ocelotgui/blob/master/PKGBUILD

**Comment by pgulutzan** [comment]
The fix has been incorporated in the latest release. The announcement is: http://ocelot.ca/blog/blog/2022/06/09/ocelotgui-version-1-7/. I am closing this but please report a new bug if anything else comes up.
